[tool.poetry]
name = "fwd-python-http"
version = "0.1.0"
description = ""
authors = ["Fialkaksu <fialkaksu1984@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
jinja2 = "^3.1.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
